# name: First Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   hello_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Say Hello
#         run: echo "Hello world"

#   bye_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Say Bye
#         run: echo "Bye world"

