# name: Marketplace and Reusable Workflows
# run-name: "${{ github.actor }} Marketplace and Reuse Run"

# on:
#   push:
#     branches:
#       - main

# jobs:
#   setup-python-job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Show Python version
#         run: python --version